### ISSUE TITLE
Timer class is broken

### ISSUE THREAD

**Issue by deshipu** [wipy/wipy#13]
As per http://forum.micropython.org/viewtopic.php?f=11&t=1057&p=7646 the Timer class examples from the documentation don't work and according to @danicampora the whole class needs fixing.

**Comment by deshipu** [comment]
I saw the release https://github.com/wipy/wipy/releases/tag/1.2.0 and since it mentions fixing the Timer class, I tried it immediately. Unfortunately, while I didn't get an error with `freq=50` this time, I also couldn't get a PWM signal on any pin.

It seems that as soon as I initialize the channel corresponding to a pin into PWM mode, that pin switches to `Pin.IN` mode.

```
>>> p = Pin('GP24')
>>> t = Timer(0, mode=Timer.PWM)
>>> p.init(p.ALT, alt=5)
>>> p
Pin('GP24', mode=Pin.ALT, pull=None, drive=Pin.MED_POWER, alt=5)
>>> ch = t.channel(t.A, freq=50)
>>> p
Pin('GP24', mode=Pin.IN, pull=None, drive=Pin.MED_POWER, alt=5)
```

**Comment by danicampora** [comment]
Hi @deshipu,

Please check the docs again, since the API has changed a bit. First of all Timer IDs start at 0 now (but you already got that right), also since the PWM dutcy cycle with 1% resolution was very bad, now the resolution has been change to 0.01% using fixed point, so, if you want a duty cycle of 50.15, then you have to pass 5015 as value. Also, since PWM pins are fixed, when creating a PWM channel the corresponding Pin is automatically configured in PWM mode. Try this:

``` python
from machine import Timer

tim = Timer(0, mode=Timer.PWM)
ch = tim.channel(Timer.A, freq=50, duty_cycle=5000)
```

And that will create a 50Hz duty cycle PWM signal on GP24 with a 50% duty cycle.

Docs link: https://micropython.org/resources/docs/en/latest/wipy/library/machine.Timer.html

Cheers,
Daniel

P.S.: Sorry for the super long delay on this fix...

**Comment by bulislaw** [comment]
Ha! It works now, thanks :) Just one one day after I got my servo!

**Comment by danicampora** [comment]
Haha awesome! Post some videos if you can :-)

Cheers,
Daniel
